### ISSUE TITLE
UI defines needs some formatting

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#12]
`f\ui\defines.hpp` has a lot of wasted lines. Things like the following need to be shortened to reduce size and keep my OCD at bay.

**From this:**
```
colorSelectRight[] = 
{
	0,
	0,
	0,
	1
};
```

**To this:**
```
colorSelectRight[] = {0,0,0,1};
```

Preferably spaces between `=`.

**Comment by CER10TY** [comment]
Ideally you shouldn't mess with the defines.hpp as this is auto-generated by A3's GUI Editor. Even though it's always the same, custom arguments like colorBackground[] = {}; should instead be defined in the individual dialogs.hpp (defines.hpp is the master file). GET YOUR OCD IN CHECK, KINGSLEY. DON'T LOOK AT IT.

**Comment by jameslkingsley** [comment]
No I exported this a while ago and tweaked it to make it look like Arma 3's design style. It's totally safe to edit, it's just classes. The colours are setup to use whatever the user has defined in their colour scheme.

**Comment by CER10TY** [comment]
Yeah I know that it's safe to edit but really the export file should just be left as is, since if there's changes to be made to individual design elements they should be defined in that element's dialogs.hpp instead. It all depends on how it's implemented obviously but if we're adding on more dialogs later then theoretically there's a risk you might screw them up when editing the defines instead of the individual dialogs.hpp
