### ISSUE TITLE
Revamp briefing timer

### ISSUE THREAD

**Issue by CER10TY** [ARCOMM/ARCMF#67]
As per session townhall yesterday we need to work on briefing timer. What I've noticed is that ARC_fnc_hint basically uses hintSilent (which runs for 30 seconds until it disappears, engine-wise) and shuts it down after N duration specified. 

I'd personally switch over to hint (for a ping) and letting it run for 30 seconds before running it again, as this guarantees that players will continously see the hint and get a ping every 30 seconds reminding them that safestart is on.

**Comment by jameslkingsley** [comment]
I don't intend to change it back to the old count-down however. I'll make a maximum briefing stage limit that mission makers can set and when it hits that the briefing stage will end. Also I'm going to make a small UI feature in the map that shows the time since the mission started (from the server) so even during the mission you can open the map and see top right how long the mission has been running for.

**Comment by CER10TY** [comment]
Briefing timer still doesn't work, not showing up in the top-right on map view.

**Comment by jameslkingsley** [comment]
Closing this and moving it to ARCMF2.
