### ISSUE TITLE
Convert framework to a mod for better backwards compatibility

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARCMF#83]
Essential the init and description should just include files from a mod and then we can keep all framework code in the mod (using the ACE/CBA setup). This way we get even smaller mission files and missions won't be version dependent. They'll all contain general mission stuff like loadouts, briefings etc. but the underlying "engine" of the framework is kept as a mod. This also means we'd be able to use ARCMF functions in missions that aren't made with ARCMF.

**Mission:**
* Mission.sqm (obviously)
* Loadouts
* Briefings
* Config
* Group ID's / Markers (perhaps overhaul to a config-based solution)

**Mod:**
* Functions & UI
* Pretty much **everything** else
* Expose almost everything with CBA event handlers

**Comment by CER10TY** [comment]
I don't really see a point with this to be honest. Mission size, at this point, is a non-issue and you are going to run into trouble sooner or later when adding new features that need to interact with the framework (SQF code base) in a way, making it version dependant. 

Additionally, you are essentially exposing the majority of the file size (which we want to cut down on) to the 'general public' by making it a mod. So yes, the mission size itself may be cut additionally from 500kb to maybe 250kb, but you have now added 250kb to the modset. Additionally, we may be forced to adhere to the weekly mod update schedule if we want to push out updates for the framework. Whilst this shouldn't be an issue most of the time, it may be in certain circumstances. I can specifically see hotfixes quickly become an issue.

It's possible if done right, but I see little gain in it because the customer support side, if you want to call it that, isn't going to get better either. Sure, people don't have to go through the hassle of updating certain bits and pieces manually if they make a mission with v1 but suddenly v2 gets pushed out (since it is most likely a behind a scenes update, eg UI) but you'll still have people with loadout issues etc etc. You get the point. 

I do like argument of using ARCMF functions outside of ARCMF, but our functions library would probably need some work.

**Comment by CER10TY** [comment]
Just to iterate on the hotfix issue: Let's say there's an issue with standard OPFOR loadout and mission X is using that. We fix it with a hotfix. Now ideally, the mission maker of X gets the hotfix in, pushes the mission to BLaw again and he uploads it to the server. That's 2 people exposed to the whole process, took maybe 5 minutes to fix, mission playable.

On the other hand, if you now have to push this to the modset, you will expose 60+ people to a mod update that they absolutely need. If that update doesn't happen due to the aforementioned weekly update schedule (and somebody doesn't want to push out a hotfix on Saturday evening for example, which is understandable), the mission is unplayable. If it does happen, you could still get people who haven't updated their modset. Essentially, you've made a 5 minute process a gamble due to the mod configuration approach.

I'm not saying this is everyday stuff, and this is an "extreme" case scenario, but this can and will happen at some point down the road.

**Comment by jameslkingsley** [comment]
I don't think there would be cases where a hotfix would require a mod update. The stuff that goes in the mod would be stuff that the mission maker will **never** change. Sticking to the mod update schedule for this is fine as long as the mod is rigorously tested and is deemed stable. If we need to update the mission side of it, then we can do that and just tell the mission maker to update some stuff on their end.

The F folder currently takes up around 450KB which is a lot when it comes to loading it in-game. Also we could implement a required version thing on the mission side, so if we change something that depends on the mod/mission to have it, then we can say this mission requires the mod to be version X onward etc.

I think the best way to look at it is being a code and asset library. We'd be able to add sounds, lots more themes etc. to the mod without cluttering up the mission file. It's a lot of work for sure, but it would make a missions lifetime significantly longer. Currently missions are played once and in about 2 weeks they're too old to play again (unless we want to play on an older version of the framework, things broken etc.). With this solution, every mission can be replayed providing the loadouts are still valid.
