### ISSUE TITLE
Rework briefing to either html or restructure tabs

### ISSUE THREAD

**Issue by CER10TY** [ARCOMM/ARCMF#85]
Opened as broad topic on popular demand, all relevant points should be gathered here.

Right now HTML (back to Arma1 bois) seems like a nice option.

**Comment by CER10TY** [comment]
@edelle also brought up a good point to restructure briefing to 1 page instead of tabs, however this would severely limit briefing length as scrolling may not look as pretty. 

Example screenshot:
http://images.akamai.steamusercontent.com/ugc/439489832363596725/B9CFBC12008FD05C1C025940648774FE07A8C7B6/

**Comment by jameslkingsley** [comment]
Changing this in the current framework would be a bit of an arse ache since the tutorial video for briefing shows it different to what it would be if it were a HTML document. This is something I'd save for the new framework and for now just ignore the current briefing stuff. It's not exactly a major issue, if an issue at all right now.

**Comment by CER10TY** [comment]
Agreed, opened it up more as a courtesy than anything else because of the major "discussion" we had earlier. Might aswell push it over to ARCMF2 Issues page for later.
